api/urls.py
from django.conf.urls import url
from api import views


urlpatterns = [
    url(r'^api/items/$', views.ItemList.as_view(), name='item_list_api'),
    url(r'^api/items/(?P<pk>[0-9]+)/$',
        views.ItemDetail.as_view(), name='item_detail_api'),

    url(r'^api/rates/$', views.RateList.as_view(), name='rate_list_api'),

    url(r'^api/comments/$', views.CommentList.as_view(), name='comment_list_api'),

    url(r'^api/categories/$', views.CategoryList.as_view(), name='category_list_api'),

    url(r'^api/shops/$', views.ShopList.as_view(), name='shop_list_api'),
    url(r'^api/shops/(?P<pk>[0-9]+)/$',
        views.ShopDetail.as_view(), name='shop_detail_api'),

    url(r'^api/cart/$', views.CartList.as_view(), name='cart_list_api'),
    url(r'^api/cart/(?P<pk>[0-9]+)/$',
        views.CartDetail.as_view(), name='cart_detail_api'),

    url(r'^api/action/$', views.ActionList.as_view(), name='action_list_api'),
    url(r'^api/action/(?P<pk>[0-9]+)/$',
        views.ActionDetail.as_view(), name='action_detail_api'),


]

products/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from products import views


urlpatterns = [

    # Django views
    url(r"^shops/$", views.ShopListView.as_view(), name='shop_list'),
    url(r"^shops/(?P<pk>\w+)/$", views.ShopDetailView.as_view(), name='shop_detail'),

    url(r"^products/$", views.ItemListView.as_view(), name='products_list'),
    url(r"^products/add/$", views.ItemAddView.as_view(), name='products_add'),
    url(r"^products/(?P<pk>\w+)/$",
        views.ItemDetailView.as_view(), name='products_show'),
    url(r"^products/(?P<pk>\w+)/edit/$",
        views.ItemEditView.as_view(), name='products_edit'),
    url(r"^products/(?P<pk>\w+)/delete/$",
        views.ItemDeleteView.as_view(), name='products_delete'),
    url(r"^products/(?P<pk>\w+)/action/$",
        views.ItemActionView.as_view(), name='products_action'),

    url(r"^products/(?P<pk>\w+)/comments/add/$",
        views.AddCommentView.as_view(), name='comment_add'),
    url(r"^products/(?P<pk>\w+)/rates/add/$",
        views.AddRateView.as_view(), name='rate_add'),


    # Angular views
    url(r"^products_ang/$", TemplateView.as_view(
        template_name='api/products/index.html'
    ), name='products_index_ang'),
    url(r"^products_ang/list/$", TemplateView.as_view(
        template_name='api/products/list.html'
    ), name='products_list_ang'),
    url(r"^products_ang/show/$", TemplateView.as_view(
        template_name='api/products/detail.html'
    ), name='products_detail_ang'),
    url(r"^products_ang/edit/$", TemplateView.as_view(
        template_name='api/products/modify.html'
    ), name='products_edit_ang'),
    url(r"^products_ang/action/add/$", TemplateView.as_view(
        template_name='api/action/action_form.html'
    ), name='products_action_add_ang'),
    url(r"^categories_ang/$", TemplateView.as_view(
        template_name='api/categories/index.html'
    ), name='categories_list_ang'),


    # Haystack search
    url(r'^search/', include('haystack.urls')),


]

test_case/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Home view
    url(r"^$", TemplateView.as_view(
        template_name='home.html'
    ), name='home'),

    # Debug view for tests
    url(r"^test/", TemplateView.as_view(
        template_name='test.html'
    ), name='test'),

    url(r'^', include('products.urls')),
    url(r'^', include('categories.urls')),
    url(r'^', include('cart.urls')),
    url(r'^', include('my_auth.urls')),
    url(r'^', include('api.urls')),

    # Social
    url('', include('social.apps.django_app.urls', namespace='social'))


]

products/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from categories.models import Category
from core.models import TimeStampedModel
from products.managers import RateManager

# Create your models here.


class Item(TimeStampedModel):
    name = models.CharField(_("Name of item"), max_length=100, blank=False)
    price = models.PositiveIntegerField(_("Price"), blank=False)
    image_url = models.URLField(_("Link to image"), blank=True, max_length=50)
    categories = models.ManyToManyField(Category, blank=True)
    description = models.CharField(
        _("Description"), max_length=1000, blank=False)
    quantity = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='items')

    def __str__(self):
        return self.name

    # Min count of quantity items for quantity-message
    def get_min_quantity(self):
        return 10


class Comment(TimeStampedModel):
    username = models.CharField(_("Username"), max_length=50, blank=False)
    message = models.CharField(_("Comment"), max_length=1000, blank=False)
    item = models.ForeignKey(Item, related_name='comments')

    def __str__(self):
        return self.message


class Rate(models.Model):
    value = models.PositiveIntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    item = models.ForeignKey(Item, related_name='rates')

    # add our custom model manager
    objects = RateManager()

    def __unicode__(self):
        return self.value


class Action(models.Model):
    item = models.OneToOneField(Item)
    shop = models.ForeignKey(settings.AUTH_USER_MODEL)
    description = models.CharField(max_length=1000)
    new_price = models.PositiveIntegerField()
    period_from = models.DateField()
    period_to = models.DateField()

    def __unicode__(self):
        return self.item

api/views.py
from django.http import Http404
from django.utils.datastructures import MultiValueDictKeyError
from django.core.exceptions import ObjectDoesNotExist
from rest_framework import generics, status, permissions
from rest_framework.pagination import PageNumberPagination
from rest_framework.views import APIView
from rest_framework.response import Response
from my_auth.models import MyUser
from products.models import Item, Action
from products import cache
from products.service import RateService
from cart.service import CartService
from api import serializers
from api.utils import addItemIdToSession, removeItemIdFromSession
from api.permissions import IsAuthorOrReadOnly, ShopIsAuthorOrReadOnly, IsAuthorOfActionOrReadOnly, IsItemOutOfStock
from categories.cache import CategoryCache
from my_auth.cache import ShopDetailCache
from haystack.query import SearchQuerySet


# Standard Pagination class
class StandardResultsSetPagination(PageNumberPagination):
    page_size = 9
    page_size_query_param = 'page_size'
    max_page_size = 1


# Comments pagination
class CommentsSetPagination(StandardResultsSetPagination):
    page_size = 4


# Item list
class ItemList(generics.GenericAPIView):
    pagination_class = StandardResultsSetPagination
    serializer_class = serializers.ItemSerializer

    def get(self, request):

        sort = request.GET.get('sort', '-id')

        try:
            request.GET["category"]
        except MultiValueDictKeyError:
            queryset = SearchQuerySet().models(Item).order_by(sort)
        else:
            queryset = SearchQuerySet().models(Item).filter(
                categories__in=[request.GET["category"]]).order_by('-id')

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = serializers.ItemSerializer(queryset, many=True)
        return Response(serializer.data)


# Item detail
class ItemDetail(generics.RetrieveAPIView, generics.UpdateAPIView,
                 generics.DestroyAPIView):
    serializer_class = serializers.ItemDetailSerializer
    permission_classes = (IsAuthorOrReadOnly, )

    def get_object(self):

        lookup_url_kwarg = self.lookup_url_kwarg or self.lookup_field
        filter_kwargs = {self.lookup_field: self.kwargs[lookup_url_kwarg]}
        obj = cache.ProductDetailCache().get(id=filter_kwargs['pk'])
        self.check_object_permissions(self.request, obj)

        return obj


# list of categories
class CategoryList(generics.GenericAPIView):

    pagination_class = StandardResultsSetPagination
    serializer_class = serializers.CategorySerializer

    def get(self, request):

        queryset = CategoryCache().get(parent_category_id__isnull=True)
        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = serializers.ItemSerializer(queryset, many=True)
        return Response(serializer.data)


# Comments list
class CommentList(generics.GenericAPIView):

    pagination_class = CommentsSetPagination
    serializer_class = serializers.CommentSerializer

    def get(self, request):
        comments = cache.CommentCache().get()

        page = self.paginate_queryset(comments)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = serializers.CommentSerializer(comments, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = serializers.CommentSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# Rating list
class RateList(APIView):
    permission_classes = (permissions.IsAuthenticated, )

    def get(self, request):
        rates = cache.RateCache().get()
        serializer = serializers.RateSerializer(rates, many=True)
        return Response(serializer.data)

    def post(self, request):

            item_id = request.data.get('item', False)
            rate = RateService().get_rate(request.user, item_id)
            serializer = serializers.RateSerializer(
                data=request.data, instance=rate)
            if serializer.is_valid():
                serializer.save(user=self.request.user)
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

"""List of shop-users"""


class ShopList(generics.GenericAPIView):
    pagination_class = StandardResultsSetPagination
    serializer_class = serializers.ShopSerializer

    def get(self, request):

        queryset = SearchQuerySet().models(MyUser).order_by('-id')
        page = self.paginate_queryset(queryset)

        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = serializers.ShopSerializer(queryset, many=True)
        return Response(serializer.data)


# Detail of shop-users
class ShopDetail(generics.RetrieveAPIView):
    serializer_class = serializers.ShopDetailSerializer

    def get_object(self):

        lookup_url_kwarg = self.lookup_url_kwarg or self.lookup_field
        filter_kwargs = {self.lookup_field: self.kwargs[lookup_url_kwarg]}
        obj = ShopDetailCache().get(id=filter_kwargs['pk'])
        self.check_object_permissions(self.request, obj)

        return obj


""" List of items in cart for auth user """


class CartList(generics.GenericAPIView):
    pagination_class = StandardResultsSetPagination
    serializer_class = serializers.CartSerializer
    permission_classes = (permissions.IsAuthenticated, IsItemOutOfStock)

    def get(self, request):

        queryset = CartService().get_cart(self.request.user)
        page = self.paginate_queryset(queryset)

        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = serializers.CartSerializer(queryset, many=True)
        return Response(serializer.data)

    def post(self, request):
        item_id = request.POST.get('item', False)
        item = CartService().get_cart(request.user, item_id=item_id).first()
        serializer = serializers.CartSerializer(
            data=request.data, instance=item)
        if serializer.is_valid():
            serializer.save(user=self.request.user)

            # add item id to session
            addItemIdToSession(request)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# Detail of cart. ID is item_id
class CartDetail(generics.RetrieveAPIView, generics.UpdateAPIView,
                 generics.DestroyAPIView):

    permission_classes = (permissions.IsAuthenticated, )
    serializer_class = serializers.CartSerializer

    def get_object(self):

        lookup_url_kwarg = self.lookup_url_kwarg or self.lookup_field
        filter_kwargs = {self.lookup_field: self.kwargs[lookup_url_kwarg]}
        obj = CartService().get_cart(self.request.user, item_id=filter_kwargs['pk']).first()
        if obj is None:
            raise Http404
        self.check_object_permissions(self.request, obj)

        return obj

    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        self.perform_destroy(instance)

        # remove item id from session
        removeItemIdFromSession(request, kwargs['pk'])
        return Response(status=status.HTTP_204_NO_CONTENT)


# Action list and details for current auth user
class ActionList(generics.GenericAPIView):
    pagination_class = StandardResultsSetPagination
    serializer_class = serializers.ActionSerializer
    permission_classes = (ShopIsAuthorOrReadOnly, permissions.IsAuthenticated, )

    def get(self, request):

        queryset = self.request.user.action_set.all()
        page = self.paginate_queryset(queryset)

        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = serializers.ActionSerializer(queryset, many=True)
        return Response(serializer.data)

    def post(self, request):
        try:
            action = self.request.user.action_set.get(
                item__id=request.data["item"])
        except (ObjectDoesNotExist, AttributeError):
            action = None
        serializer = serializers.ActionSerializer(
            data=request.data, instance=action)
        if serializer.is_valid():
            serializer.save(shop=self.request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# Detail of cart. ID is item_id
class ActionDetail(generics.RetrieveAPIView, generics.UpdateAPIView,
                 generics.DestroyAPIView):

    permission_classes = (IsAuthorOfActionOrReadOnly, permissions.IsAuthenticated)
    serializer_class = serializers.ActionSerializer

    def get_object(self):

        lookup_url_kwarg = self.lookup_url_kwarg or self.lookup_field
        filter_kwargs = {self.lookup_field: self.kwargs[lookup_url_kwarg]}
        obj = Action.objects.filter(shop=self.request.user, item_id=filter_kwargs['pk']).first()
        if obj is None:
            raise Http404
        self.check_object_permissions(self.request, obj)

        return obj

api/templates/api/products/index.html
{% extends 'layout.html' %}
{% load i18n %}
{% load staticfiles %}
{% block title %}
    {% trans "list of items" %}
{% endblock %}

{% block content %}

        <!-- success messages -->
        {% include 'products/partials/success_message.html' %}
        <!-- !success messages -->

        <!-- Ng-view -->
        <div ng-view></div>

{% endblock %}

api/templates/api/products/modify.html
{% load i18n %}

<div class="wrapperOnList col-lg-12 col-md-12 col-sm-12 col-xs-12" ng-if="isAuthUserIsOwner()">

    <!-- Error message -->
    <h4 class="error-comment-message" ng-repeat="(errorName,errorMessage) in errorEditItem.data">
        [[ errorName ]]:
        <ul>
            <li ng-repeat="errorMessage in errorMessage">
                [[ errorMessage ]]
            </li>
        </ul>
    </h4>

    <h1 class="item-detail-name">{% trans "Editing:" %} [[ itemDetail.name ]]</h1>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
        <li><a ui-sref="products-list">{% trans "List of items" %}</a></li>
        <li><a ui-sref="products-detail({ itemId:item.pk})">{% trans "Detail of item" %}</a></li>
        <li class="active">{% trans "Edit" %}</li>
    </ol>
    <hr>

    <!-- form for edit or delete item only by owner -->
    <form name="edit_item_form" class="form-horizontal edit_item_form" role="form" method="POST" ng-submit="editItem()">

        <div class="form-group"><label class="col-md-2 control-label" for="id_name">{% trans "Name of item" %}</label>

            <div class="col-md-7"><input class="form-control" id="id_name" maxlength="100" name="name"
                                         placeholder="name of item" required="required" title="" type="text"
                                         ng-model="itemDetail.name"></div>
            <div class="col-lg-11 col-md-10 col-sm-12 col-xs-12 text-center" ng-show="edit_item_form.name.$error.required">
                <span class="help-block-error"><strong>{% trans "This field is required." %}</strong></span>
            </div>
        </div>

        <div class="form-group"><label class="col-md-2 control-label" for="id_price">{% trans "Price" %}</label>

            <div class="col-md-7"><input class="form-control" id="id_price" max="10000000" min="0" name="price"
                                         placeholder="price" required="required" title="" type="number"
                                         ng-model="itemDetail.price"></div>
            <div class="col-lg-11 col-md-10 col-sm-12 col-xs-12 text-center" ng-show="edit_item_form.price.$error.required">
                <span class="help-block-error"><strong>{% trans "This field is required." %}</strong></span>
            </div>
        </div>

        <div class="form-group"><label class="col-md-2 control-label" for="id_price">{% trans "Quantity" %}</label>

            <div class="col-md-7"><input class="form-control"  name="quantity"
                                         placeholder="quantity" title="" type="number"
                                         ng-model="itemDetail.quantity"></div>
        </div>

        <div class="form-group"><label class="col-md-2 control-label" for="id_image_url">{% trans "Link to image" %}</label>

            <div class="col-md-7"><input class="form-control" id="id_image_url" maxlength="200" name="image_url"
                                         placeholder="link to image" title="" type="url"
                                         ng-model="itemDetail.image_url"></div>
        </div>

        <div class="form-group"><label class="col-md-2 control-label" for="id_description">{% trans "Description" %}</label>

            <div class="col-md-7"><textarea class="form-control" cols="40" id="id_description" name="description"
                                            placeholder="description" required="required" rows="10"
                                            title="" ng-model="itemDetail.description"></textarea></div>
            <div class="col-lg-11 col-md-10 col-sm-12 col-xs-12 text-center" ng-show="edit_item_form.description.$error.required">
                <span class="help-block-error"><strong>{% trans "This field is required." %}</strong></span>
            </div>

        </div>

        <div class="form-group"><label class="col-md-2 control-label" for="id_description">{% trans "Delete item" %}</label>

            <div class="col-md-7">
                <button class="btn btn-danger" type="button" ng-click="deleteItem()">{% trans "Delete item" %}</button>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6 col-md-offset-2 text-center">
                <button id="testButton" type="submit" class="btn btn-primary" name="submit">{% trans "Edit item" %}</button>
            </div>
        </div>
    </form>

    <!-- Flash error messages -->
   <div flash-message="4000"></div>

</div>

<!-- non-author permission message -->
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center" ng-if="!isAuthUserIsOwner()">
    <h1>{% trans "You don't have permission to edit this item!" %}</h1>
</div>