api/urls.py
from django.conf.urls import url
from api import views


urlpatterns = [
    url(r'^api/items/$', views.ItemList.as_view(), name='item_list_api'),
    url(r'^api/items/(?P<pk>[0-9]+)/$',
        views.ItemDetail.as_view(), name='item_detail_api'),

    url(r'^api/rates/$', views.RateList.as_view(), name='rate_list_api'),

    url(r'^api/comments/$', views.CommentList.as_view(), name='comment_list_api'),

    url(r'^api/categories/$', views.CategoryList.as_view(), name='category_list_api'),

    url(r'^api/shops/$', views.ShopList.as_view(), name='shop_list_api'),
    url(r'^api/shops/(?P<pk>[0-9]+)/$',
        views.ShopDetail.as_view(), name='shop_detail_api'),

    url(r'^api/cart/$', views.CartList.as_view(), name='cart_list_api'),
    url(r'^api/cart/(?P<pk>[0-9]+)/$',
        views.CartDetail.as_view(), name='cart_detail_api'),

    url(r'^api/action/$', views.ActionList.as_view(), name='action_list_api'),
    url(r'^api/action/(?P<pk>[0-9]+)/$',
        views.ActionDetail.as_view(), name='action_detail_api'),


]

categories/urls.py
from django.conf.urls import url
from categories import views


urlpatterns = [

    # Categories views
    url(r"^categories/add/$", views.CategoryAddView.as_view(), name='categories_add'),
    url(r"^categories/$", views.CategoryListView.as_view(), name='categories_list'),


]

test_case/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Home view
    url(r"^$", TemplateView.as_view(
        template_name='home.html'
    ), name='home'),

    # Debug view for tests
    url(r"^test/", TemplateView.as_view(
        template_name='test.html'
    ), name='test'),

    url(r'^', include('products.urls')),
    url(r'^', include('categories.urls')),
    url(r'^', include('cart.urls')),
    url(r'^', include('my_auth.urls')),
    url(r'^', include('api.urls')),

    # Social
    url('', include('social.apps.django_app.urls', namespace='social'))


]

categories/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Category(models.Model):
    name = models.CharField(_("Name"), max_length=50, blank=False)
    parent_category = models.ForeignKey("self", blank=True, null=True)

    def __str__(self):
        return self.name

categories/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from categories.models import Category
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from categories.utils import categories_as_choices


class AddCategory(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AddCategory, self).__init__(*args, **kwargs)
        self.fields['parent_category'].choices = categories_as_choices()

        # for empty choice
        self.fields['parent_category'].choices.insert(0, ('', '---------'))

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = '#'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-7'

        self.helper.add_input(Submit('submit', _('Add/edit category'),
                                     css_class='btn btn-default btn-md col-md-offset-5'))

    class Meta:
        model = Category
        fields = ('name', 'parent_category', )

        help_texts = {
            'parent_category': _('Choose parent category if you want.'),
        }

        labels = {
            'parent_category': _('Parent Category'),
        }

categories/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from categories import cache
from categories.models import Category
from categories.forms import AddCategory
from products.views import LoginRequiredMixin


# Category list
class CategoryListView(ListView):
    template_name = 'categories/index.html'
    context_object_name = 'categories'
    paginate_by = 10

    def get_queryset(self):
        return cache.CategoryCache().get(parent_category_id__isnull=True)


# For add new category
class CategoryAddView(LoginRequiredMixin, CreateView):
    model = Category
    template_name = 'categories/modify.html'
    form_class = AddCategory
    success_msg = _('Category added!')

    def get_context_data(self, **kwargs):
        context = super(CategoryAddView, self).get_context_data(**kwargs)
        context['foo'] = _('Add')
        return context

    def form_valid(self, form):
        messages.success(self.request, self.success_msg)
        return super(CategoryAddView, self).form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse("categories_list_ang")

categories/templates/categories/index.html
{% extends 'layout.html' %}
{% load i18n %}
{% load staticfiles %}
{% block title %}
    {% trans "List of categories" %}
{% endblock %}

{% block content %}
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-6 col-md-9 col-sm-9 col-xs-12">
                        <h1 id="test">{% trans "List of categories" %}</h1>
                    </div>
                    <div class="button-add-something col-lg-6 col-md-3 col-sm-3 col-xs-12">
                        <a href="{% url 'categories_add' %}"
                           class="btn btn-warning pull-right">{% trans "Add category" %}</a>
                    </div>
                </div>
            </div>
        </div>

        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
            <li class="active">{% trans "List of categories" %}</li>
        </ol>
        <hr>

        <div class="row">
            <!-- success messages -->
            {% include 'products/partials/success_message.html' %}
            <!-- !success messages -->

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                {% for note in categories %}
                    <div class="main-list col-lg-4 col-ms-4 col-sm-6 col-xs-12">
                            <div class="row">
                                <div class="notes_labels col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <h2>{% trans "ID:" %}{{ note.id }}</h2>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <h4>{% trans "Name:" %}{{ note.name|truncatechars:30 }}</h4>
                                </div>
                            </div>
                            <h4>{% trans "Sub:" %}</h4>
                            <ul>
                                {% for sub in note.category_set.all %}
                                    <li>{{ sub }}</li>
                                {% empty %}
                                    <h4>{% trans "Sub categories doesnt exists" %}</h4>
                                {% endfor %}
                            </ul>
                    </div>
                {% empty %}
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        {% trans "Categories doesn't add yeat." %}
                    </div>
                {% endfor %}
            </div>
        {% if is_paginated %}
            <nav>
                <ul class="pager">
                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a></li>
                    {% endif %}
                    {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        {% endif %}

{% endblock %}

categories/templates/categories/modify.html
{% extends 'layout.html' %}
{% load i18n %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block title %}
    {{ foo }} {% trans "category" %}
{% endblock %}

{% block content %}

    <h1>{{ foo }} {% trans "category" %}</h1>
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
        <li><a href="#">{% trans "Categories" %}</a></li>
        <li class="active">{{ foo }} {% trans "category" %}</li>
    </ol>
    <hr>
    <div class="col-md-8 col-sm-10">

            {% crispy form %}

    </div>

{% endblock %}