api/urls.py
from django.conf.urls import url
from api import views


urlpatterns = [
    url(r'^api/items/$', views.ItemList.as_view(), name='item_list_api'),
    url(r'^api/items/(?P<pk>[0-9]+)/$',
        views.ItemDetail.as_view(), name='item_detail_api'),

    url(r'^api/rates/$', views.RateList.as_view(), name='rate_list_api'),

    url(r'^api/comments/$', views.CommentList.as_view(), name='comment_list_api'),

    url(r'^api/categories/$', views.CategoryList.as_view(), name='category_list_api'),

    url(r'^api/shops/$', views.ShopList.as_view(), name='shop_list_api'),
    url(r'^api/shops/(?P<pk>[0-9]+)/$',
        views.ShopDetail.as_view(), name='shop_detail_api'),

    url(r'^api/cart/$', views.CartList.as_view(), name='cart_list_api'),
    url(r'^api/cart/(?P<pk>[0-9]+)/$',
        views.CartDetail.as_view(), name='cart_detail_api'),

    url(r'^api/action/$', views.ActionList.as_view(), name='action_list_api'),
    url(r'^api/action/(?P<pk>[0-9]+)/$',
        views.ActionDetail.as_view(), name='action_detail_api'),


]

products/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from products import views


urlpatterns = [

    # Django views
    url(r"^shops/$", views.ShopListView.as_view(), name='shop_list'),
    url(r"^shops/(?P<pk>\w+)/$", views.ShopDetailView.as_view(), name='shop_detail'),

    url(r"^products/$", views.ItemListView.as_view(), name='products_list'),
    url(r"^products/add/$", views.ItemAddView.as_view(), name='products_add'),
    url(r"^products/(?P<pk>\w+)/$",
        views.ItemDetailView.as_view(), name='products_show'),
    url(r"^products/(?P<pk>\w+)/edit/$",
        views.ItemEditView.as_view(), name='products_edit'),
    url(r"^products/(?P<pk>\w+)/delete/$",
        views.ItemDeleteView.as_view(), name='products_delete'),
    url(r"^products/(?P<pk>\w+)/action/$",
        views.ItemActionView.as_view(), name='products_action'),

    url(r"^products/(?P<pk>\w+)/comments/add/$",
        views.AddCommentView.as_view(), name='comment_add'),
    url(r"^products/(?P<pk>\w+)/rates/add/$",
        views.AddRateView.as_view(), name='rate_add'),


    # Angular views
    url(r"^products_ang/$", TemplateView.as_view(
        template_name='api/products/index.html'
    ), name='products_index_ang'),
    url(r"^products_ang/list/$", TemplateView.as_view(
        template_name='api/products/list.html'
    ), name='products_list_ang'),
    url(r"^products_ang/show/$", TemplateView.as_view(
        template_name='api/products/detail.html'
    ), name='products_detail_ang'),
    url(r"^products_ang/edit/$", TemplateView.as_view(
        template_name='api/products/modify.html'
    ), name='products_edit_ang'),
    url(r"^products_ang/action/add/$", TemplateView.as_view(
        template_name='api/action/action_form.html'
    ), name='products_action_add_ang'),
    url(r"^categories_ang/$", TemplateView.as_view(
        template_name='api/categories/index.html'
    ), name='categories_list_ang'),


    # Haystack search
    url(r'^search/', include('haystack.urls')),


]

test_case/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Home view
    url(r"^$", TemplateView.as_view(
        template_name='home.html'
    ), name='home'),

    # Debug view for tests
    url(r"^test/", TemplateView.as_view(
        template_name='test.html'
    ), name='test'),

    url(r'^', include('products.urls')),
    url(r'^', include('categories.urls')),
    url(r'^', include('cart.urls')),
    url(r'^', include('my_auth.urls')),
    url(r'^', include('api.urls')),

    # Social
    url('', include('social.apps.django_app.urls', namespace='social'))


]

cart/models.py
from django.db import models
from products.models import Item
from django.conf import settings


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    item = models.ForeignKey(Item)

    def __unicode__(self):
        return self.user

products/forms.py
# -*- coding: utf-8 -*-

from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from django.forms.extras.widgets import SelectDateWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, Fieldset
from crispy_forms.bootstrap import PrependedText
from products import models
from my_auth.models import MyUser


class MyLoginForm(AuthenticationForm):

    username = forms.CharField(label=_('username'))
    password = forms.CharField(label=_('password'), widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(MyLoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = '#'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-7'

        self.helper.add_input(Submit('submit', 'Sign In',
                                     css_class='btn btn-default btn-md col-md-offset-5'))

        self.helper.layout = Layout(
            Field(
                'username', placeholder='Input your login'
            ),
            Field(
                'password', placeholder='Input your password'
            )
        )


class MyRegForm(UserCreationForm):
    form_name = 'reg_form'
    error_messages = {
        'password_mismatch': "Passwords mismatch",
    }
    username = forms.CharField(help_text='Max 30 characters')
    password1 = forms.CharField(min_length=6, label=_('password'), widget=forms.PasswordInput,
                                help_text=_("Min 6 characters"))
    password2 = forms.CharField(min_length=6, label=_('password again'),
                                widget=forms.PasswordInput)
    last_name = forms.CharField(max_length=50, label=_('last name'))
    first_name = forms.CharField(max_length=50, label=_('first name'))
    email = forms.EmailField(label=_('Email'), required=True,)

    def __init__(self, *args, **kwargs):
        super(MyRegForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = '#'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-7'

        self.helper.add_input(Submit('submit', _('Sign Up'),
                                     css_class='btn btn-default btn-md col-md-offset-5'))

    class Meta:
        model = MyUser
        fields = ('last_name', 'first_name', 'username',
                  'email', 'password1', 'password2',)

    def save(self, commit=True):
        user = super(MyRegForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user


class AddComment(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea, label=_('comment'))

    class Meta:
        model = models.Comment
        fields = ('username', 'message', )


class AddRate(forms.ModelForm):
    value = forms.IntegerField(max_value=10, min_value=1, label=_('rate item'))

    class Meta:
        model = models.Rate
        fields = ('value', )


class ModifyItem(forms.ModelForm):
    price = forms.IntegerField(
        max_value=10000000, min_value=0, label=_('Price'))
    description = forms.CharField(
        widget=forms.Textarea, label=_('Description'))

    quantity = forms.IntegerField(
        min_value=0, label=_('Quantity'), required=False)

    def __init__(self, *args, **kwargs):
        super(ModifyItem, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = '#'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-7'

        self.helper.add_input(Submit('submit', _('Add/edit item'),
                                     css_class='btn btn-default btn-md col-md-offset-5'))

        self.helper.layout = Layout(
            Fieldset(
                'Add item',
                'name',
                'image_url',
                'categories',
                'description',
                'quantity',
            ),
            PrependedText(
                'price', '$'
            ),

        )

    class Meta:
        model = models.Item
        fields = ('name', 'price', 'image_url',
                  'categories', 'description', 'quantity')


class ModifyAction(forms.ModelForm):
    period_from = forms.DateTimeField(widget=SelectDateWidget())
    period_to = forms.DateTimeField(widget=SelectDateWidget())

    def __init__(self, *args, **kwargs):
        super(ModifyAction, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = '#'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-7'

        self.helper.add_input(Submit('submit', _('Add/edit action'),
                                     css_class='btn btn-default btn-md col-md-offset-5'))

    class Meta:
        model = models.Action
        fields = ('item', 'shop', 'description',
                  'new_price', 'period_from', 'period_to', )

products/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from products import cache
from products.service import RateService
from .models import Rate, Item
from products import forms
from products import models
from products import utils
from products.validators import if_user_not_a_shop
from my_auth.models import MyUser
from my_auth.cache import ShopDetailCache
from haystack.query import SearchQuerySet


# For redirect if not Auth
class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view, login_url='/auth/login/')


# For list of items
class ItemListView(View):
    template_name = 'products/products/index.html'

    def get(self, request):
        # Sort by category
        category = request.GET.get('category', False)
        if not category:
            products_list = SearchQuerySet().models(Item).all().order_by('-id')
        else:
            products_list = SearchQuerySet().models(Item).filter(
                categories__name=category).order_by('-id')
        # Facet
        facets = SearchQuerySet().models(Item).facet('categories').facet_counts()
        # Pagination
        paginator = Paginator(products_list, 6)
        page = request.GET.get('page')

        try:
            products_list = paginator.page(page)
        except PageNotAnInteger:
            products_list = paginator.page(1)
        except EmptyPage:
            products_list = paginator.page(paginator.num_pages)

        return render(request, self.template_name, {'products_list': products_list,
                                                    'facets': facets, })


# Item detail
class ItemDetailView(View):
    template_name = 'products/products/show.html'

    def get(self, request, **kwargs):

        # get item and current user rate to this item
        item = cache.ProductDetailCache().get(id=kwargs["pk"])
        user_rate = RateService().get_rate(request.user, item.id)

        # quantity-count message
        message_of_quantity_count = utils.message_of_quantity_items(item)
        item = utils.price_with_percent(item)

        context = {
            'comment_form': forms.AddComment,
            'rating_form': forms.AddRate(instance=user_rate),
            'average_rating': models.Rate.objects.average(item_id=item.id),
            'item': item,
            'message': message_of_quantity_count,
        }
        return render(request, self.template_name, context)


# For add new item
class ItemAddView(LoginRequiredMixin, CreateView):
    model = Item
    template_name = 'products/products/modify.html'
    form_class = forms.ModifyItem
    success_msg = _('Item added!')

    def get_context_data(self, **kwargs):
        context = super(ItemAddView, self).get_context_data(**kwargs)
        context['foo'] = _('Add')
        if_user_not_a_shop(self)  # Check if auth user is shop
        return context

    def form_valid(self, form):
        first = form.save(commit=False)
        first.user = self.request.user
        first.save()
        messages.success(self.request, self.success_msg)
        return super(ItemAddView, self).form_valid(form)

    def get_success_url(self):
        return reverse("products_index_ang")


# class for edit item
class ItemEditView(LoginRequiredMixin, UpdateView):
    model = Item
    template_name = 'products/products/modify.html'
    form_class = forms.ModifyItem
    success_msg = _('Item edited!')

    def get_context_data(self, **kwargs):
        context = super(ItemEditView, self).get_context_data(**kwargs)
        context['foo'] = _('Edit')
        if_user_not_a_shop(self)  # Check if auth user is shop
        return context

    def form_valid(self, form):
        messages.success(self.request, self.success_msg)
        return super(ItemEditView, self).form_valid(form)

    def get_success_url(self):
        return reverse("products_list")


# Delete item view
class ItemDeleteView(DeleteView):
    model = Item
    success_msg = _('Item delete!')

    def form_valid(self):
        messages.success(self.request, self.success_msg)

    def get_success_url(self):
        return reverse("products_list")


# For adding new comments to detail
class AddCommentView(View):
    form_class = forms.AddComment
    template_name = 'products/products/show.html'
    success_msg = _('Your comment added!')

    def post(self, request, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            first = form.save(commit=False)
            first.item = get_object_or_404(models.Item, id=kwargs["pk"])
            first.save()
            messages.success(self.request, self.success_msg)
            return HttpResponseRedirect(reverse('products_show', args=(kwargs["pk"],)))
        return render(request, self.template_name, {'form': form})


# Add rate for specific item
class AddRateView(LoginRequiredMixin, View):
    form_class = forms.AddRate
    template_name = 'products/products/show.html'
    success_msg = _('Thanks for your rating!')

    def post(self, request, **kwargs):
        item = get_object_or_404(Item, id=kwargs["pk"])
        try:
            rate = Rate.objects.get(user=request.user.id, item=item.id)
        except ObjectDoesNotExist:
            rate = None
        form = self.form_class(request.POST, instance=rate)
        if form.is_valid():
            first = form.save(commit=False)
            first.item = get_object_or_404(models.Item, id=kwargs["pk"])
            first.user = request.user
            first.save()
            messages.success(self.request, self.success_msg)
            return HttpResponseRedirect(reverse('products_show', args=(kwargs["pk"],)))
        return render(request, self.template_name, {'form': form})


# List of shops
class ShopListView(View):
    template_name = 'products/shops/index.html'

    def get(self, request):

        shops = SearchQuerySet().models(MyUser).filter(is_shop=True).order_by('-id')

        # Pagination
        paginator = Paginator(shops, 6)
        page = request.GET.get('page')

        try:
            shops = paginator.page(page)
        except PageNotAnInteger:
            shops = paginator.page(1)
        except EmptyPage:
            shops = paginator.page(paginator.num_pages)

        return render(request, self.template_name, {'shops': shops})


# Shop detail
class ShopDetailView(View):
    template_name = 'products/shops/show.html'

    def get(self, request, **kwargs):
        shop = ShopDetailCache().get(id=kwargs["pk"])
        context = {
            'shop': shop,
        }
        return render(request, self.template_name, context)


""" View for add/edit action for item """


class ItemActionView(CreateView):
    model = models.Action
    template_name = 'products/actions/modify.html'
    form_class = forms.ModifyAction
    success_msg = _('Action add!')

    def get_context_data(self, **kwargs):
        context = super(ItemActionView, self).get_context_data(**kwargs)
        context['foo'] = _('Add')
        return context

    def form_valid(self, form):
        messages.success(self.request, self.success_msg)
        return super(ItemActionView, self).form_valid(form)

    def get_success_url(self):
        return reverse("products_list_ang")

products/templates/products/partials/footer.html
<div class="col-lg-12 col-md-12 col-sm-12 col-lg-12">
    <div class="navbar-fixed-bottom  navbar-inverse container-fluid">
        <div class="footer-text text-center">
            <a class="navbar-brand" href="#">footer</a>
        </div>
    </div>
</div>

products/templates/products/partials/form_errors.html
{% if form.errors %}
    <div class="col-md-12">
        <div class="panel-body">
            <div class="alert alert-danger">
                <ul>
                    {{ form.errors }}
                </ul>
            </div>
        </div>
    </div>
{% endif %}

products/templates/products/partials/nav.html
{% load i18n %}
{% load activelink %}

<nav class="navbar navbar-default" bs-navbar>
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed pull-left" data-toggle="collapse"
                    data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {% if not user.is_authenticated %}
                <ul id="login_nav" class="nav navbar-nav hidden-lg hidden-md hidden-sm pull-right">
                    <li><a href="{% url 'login' %}">{% trans "Sign In" %}</a>
                    </li>
                </ul>
            {% else %}

                <ul id="login_nav" class="nav navbar-nav hidden-lg hidden-md hidden-sm pull-right">
                    <li id="cart-on-nav-xs" class="nav-cart">
                        <a href="{% url 'cart_list' %}">
                            <i class="fa fa-shopping-cart fa-3x"></i>
                            <span class="badge">{{ request.session.in_cart|wordcount }}</span>
                        </a>
                    </li>
                </ul>
            {% endif %}
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li ui-sref-active="active">
                    <a ui-sref="home">{% trans "Home" %}</a>
                </li>

                <li ui-sref-active="active">
                    <a ui-sref="shop-list">{% trans "Shops" %}</a>
                </li>

                <li ui-sref-active="active">
                    <a ui-sref="products-list">{% trans "Items" %}</a>
                </li>

                <li ui-sref-active="active">
                    <a ui-sref="categories-list">{% trans "Categories" %}</a>
                </li>
                {% if user.is_staff %}
                    <li class="hidden-sm"><a href="/admin/">Admin</a>
                    </li>
                {% endif %}
            </ul>

            <!-- nav right -->
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li id="cart-on-nav" class="nav-cart hidden-xs{% ifactive "cart_list" %} active {% endifactive %}">

                    <!-- if item exists in cart - add animated pulse-->
                        <a href="{% url 'cart_list' %}">
                            <i class="fa fa-shopping-cart fa-3x"></i>
                            <span class="badge">{{ request.session.in_cart|wordcount }}</span>
                        </a>

                    </li>

                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" role="button" aria-haspopup="true"
                           aria-expanded="false">
                            {{ user.username }} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'logout' %}">{% trans "Sign out" %}</a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li ui-sref-active="active">
                        <a ui-sref="auth-login">{% trans "Sign In" %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

products/templates/products/partials/success_message.html
{% if messages %}
    {% for message in messages %}
        <div class="messenger alert alert-success text-center animated fadeInDownBig" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}